### ISSUE TITLE
How to debug the code?

### ISSUE THREAD

**Issue by zerox12311** [blove/typescript-express-starter#11]
Hi I'm using this repo to create my project
But i want to debug step by step
How can i do??
Thanks!!

**Comment by blove** [comment]
I would suggest using VS Code. They have extensive documentation on configuring node.js with the debugger. I've used the "attach to process" launch configuration: https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by zerox12311** [comment]
Thank you!
It's work!!
